"use client";

import { useEffect, useState } from "react";
import { Eye, FilePenLine } from "lucide-react";
import CombinedServicesPage from "@/components/public/services/CombinedServicesPage";
import CompanionshipDetailsPage from "@/components/public/services/CompanionshipDetailsPage";
import EventPlanningDetailsPage from "@/components/public/services/EventPlanningDetailsPage";
import { defaultCurrentServicesContent, type CurrentServicesContent } from "@/lib/services-content";
import { getCurrentServicesContent, saveCurrentServicesContent } from "@/services/services-page.service";
import useUnsavedChanges from "@/hooks/useUnsavedChanges";

type PageKey = "main" | "companionship" | "eventPlanning";
const pages: { key: PageKey; label: string }[] = [{ key:"main",label:"Services" },{ key:"companionship",label:"Companionship" },{ key:"eventPlanning",label:"Event planning" }];
const fieldClass="mt-2 w-full rounded-md border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-800 focus:border-[#52704d] focus:outline-none focus:ring-2 focus:ring-[#52704d]/20";

export default function CurrentServicesEditor(){
  const [content,setContent]=useState<CurrentServicesContent>(defaultCurrentServicesContent); const [saved,setSaved]=useState<CurrentServicesContent>(defaultCurrentServicesContent); const [active,setActive]=useState<PageKey>("main");
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const dirty=JSON.stringify(content)!==JSON.stringify(saved); useUnsavedChanges(dirty);
  useEffect(()=>{getCurrentServicesContent().then(value=>{setContent(value);setSaved(value)}).catch(err=>setError(err instanceof Error?err.message:"Unable to load Services content.")).finally(()=>setLoading(false))},[]);
  function edit(section:PageKey,field:string,value:string){setMessage("");setContent(current=>({...current,[section]:{...current[section],[field]:value}}))}
  function editAudience(index:number,value:string){setMessage("");setContent(current=>({...current,companionship:{...current.companionship,audience:current.companionship.audience.map((item,i)=>i===index?value:item)}}))}
  async function publish(){setBusy(true);setError("");setMessage("");try{const result=await saveCurrentServicesContent(content);setContent(result);setSaved(result);setMessage("Services pages published successfully.")}catch(err){setError(err instanceof Error?err.message:"Unable to publish Services pages.")}finally{setBusy(false)}}
  function field(section:PageKey,key:string,label:string,multiline=false){const value=String(content[section][key as keyof typeof content[typeof section]]);return <label className="block text-sm font-semibold text-stone-700">{label}{multiline?<textarea rows={key==="title"?3:2} className={fieldClass} value={value} onChange={event=>edit(section,key,event.target.value)}/>:<input className={fieldClass} value={value} onChange={event=>edit(section,key,event.target.value)}/>}</label>}
  const preview=active==="main"?<CombinedServicesPage content={content}/>:active==="companionship"?<CompanionshipDetailsPage content={content}/>:<EventPlanningDetailsPage content={content}/>;
  return <section className="border-b border-stone-200 bg-[#ebe8df]">
    <header className="sticky top-0 z-40 border-b border-stone-200 bg-[#fbfaf7]/95 px-5 py-4 shadow-sm backdrop-blur md:px-8"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center gap-4"><div className="mr-auto"><p className="text-[10px] font-bold uppercase tracking-[.24em] text-[#9c7127]">Page editor</p><h1 className="font-serif text-3xl text-[#173b2c]">Services</h1></div><nav className="flex rounded-lg border border-stone-300 bg-white p-1" aria-label="Services page previews">{pages.map(page=><button key={page.key} type="button" onClick={()=>setActive(page.key)} className={`rounded-md px-4 py-2 text-sm font-semibold ${active===page.key?"bg-[#52704d] text-white":"text-stone-600 hover:bg-stone-100"}`}>{page.label}</button>)}</nav><button type="button" disabled={!dirty||busy} onClick={()=>{setContent(saved);setMessage("")}} className="rounded-md border border-stone-300 bg-white px-4 py-2.5 text-sm disabled:opacity-40">Discard</button><button type="button" disabled={!dirty||busy||loading} onClick={()=>void publish()} className="rounded-md bg-[#9d7a3c] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{busy?"Publishing…":"Publish changes"}</button></div></header>
    <div className="mx-auto grid max-w-[1700px] gap-5 p-5 xl:grid-cols-[350px_minmax(0,1fr)] xl:p-8">
      <aside className="self-start rounded-xl border border-stone-200 bg-[#fbfaf7] p-5 shadow-sm xl:sticky xl:top-28"><div className="mb-5 flex items-center gap-2 border-b border-stone-200 pb-4"><FilePenLine size={18} className="text-[#52704d]"/><div><h2 className="font-serif text-2xl text-[#173b2c]">Edit {pages.find(page=>page.key===active)?.label}</h2><p className="text-xs text-stone-500">Changes appear in the preview immediately.</p></div></div>{loading?<p className="text-sm text-stone-500">Loading content…</p>:<div className="grid gap-4">{field(active,"eyebrow","Eyebrow")}{field(active,"title","Hero title",true)}{field(active,"description","Hero description",true)}{active!=="main"&&<>{field(active,"primaryCta","Primary button")}{field(active,"secondaryCta","Secondary link")}</>}{active==="companionship"&&<>{field("companionship","hourlyRate","Hourly rate")}{field("companionship","minimum","Minimum booking")}{field("companionship","startingTotal","Starting total")}<div className="border-t border-stone-200 pt-4"><p className="mb-2 text-sm font-semibold text-stone-700">Who companionship is for</p><div className="grid gap-2">{content.companionship.audience.map((item,index)=><textarea rows={2} key={index} aria-label={`Audience item ${index+1}`} className={fieldClass} value={item} onChange={event=>editAudience(index,event.target.value)}/>)}</div></div></>}</div>}{error&&<p role="alert" className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mt-4 rounded-md bg-green-50 p-3 text-sm text-green-800">{message}</p>}</aside>
      <div className="min-w-0 overflow-hidden rounded-xl border border-stone-300 bg-white shadow-xl"><div className="flex items-center gap-2 border-b border-stone-200 bg-white px-4 py-3 text-xs font-semibold uppercase tracking-[.15em] text-stone-500"><Eye size={16}/>Live page preview</div><div aria-label={`Preview of ${active} page`} inert className="max-h-[1100px] overflow-y-auto">{preview}</div></div>
    </div>
  </section>;
}
