"use client";

import { useEffect, useState } from "react";
import { defaultCurrentServicesContent, type CurrentServicesContent } from "@/lib/services-content";
import { getCurrentServicesContent, saveCurrentServicesContent } from "@/services/services-page.service";
import useUnsavedChanges from "@/hooks/useUnsavedChanges";

const fieldClass = "mt-2 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-800 focus:border-[#52704d] focus:outline-none focus:ring-2 focus:ring-[#52704d]/20";

export default function CurrentServicesEditor() {
  const [content,setContent]=useState<CurrentServicesContent>(defaultCurrentServicesContent);
  const [saved,setSaved]=useState<CurrentServicesContent>(defaultCurrentServicesContent);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const dirty=JSON.stringify(content)!==JSON.stringify(saved); useUnsavedChanges(dirty);
  useEffect(()=>{getCurrentServicesContent().then(value=>{setContent(value);setSaved(value)}).catch(err=>setError(err instanceof Error?err.message:"Unable to load Services content.")).finally(()=>setLoading(false))},[]);
  function setSection(section:"main"|"companionship"|"eventPlanning",field:string,value:string){setContent(current=>({...current,[section]:{...current[section],[field]:value}}))}
  function setAudience(index:number,value:string){setContent(current=>({...current,companionship:{...current.companionship,audience:current.companionship.audience.map((item,i)=>i===index?value:item)}}))}
  async function save(){setBusy(true);setError("");setMessage("");try{const result=await saveCurrentServicesContent(content);setContent(result);setSaved(result);setMessage("Services content published.")}catch(err){setError(err instanceof Error?err.message:"Unable to publish Services content.")}finally{setBusy(false)}}
  const input=(section:"main"|"companionship"|"eventPlanning",field:string,label:string,multiline=false)=><label className="block text-sm font-semibold text-stone-700">{label}{multiline?<textarea rows={field==="title"?3:2} className={fieldClass} value={String(content[section][field as keyof typeof content[typeof section]])} onChange={event=>setSection(section,field,event.target.value)}/>:<input className={fieldClass} value={String(content[section][field as keyof typeof content[typeof section]])} onChange={event=>setSection(section,field,event.target.value)}/>}</label>;
  return <section className="border-b border-stone-200 bg-[#f7f3ec] p-5 md:p-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#9c7127]">Page content</p><h1 className="mt-2 font-serif text-4xl text-[#173b2c]">Services pages</h1><p className="mt-2 text-sm text-stone-600">Edit the live Services, companionship, and event-planning copy.</p></div><div className="flex gap-2"><button type="button" disabled={!dirty||busy} onClick={()=>{setContent(saved);setMessage("")}} className="rounded-lg border border-stone-300 bg-white px-4 py-2.5 text-sm disabled:opacity-40">Discard</button><button type="button" disabled={!dirty||busy||loading} onClick={()=>void save()} className="rounded-lg bg-[#52704d] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{busy?"Publishing…":"Publish changes"}</button></div></header>{loading&&<p className="mt-5 text-sm text-stone-500">Loading page content…</p>}{error&&<p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mt-5 rounded-lg bg-green-50 p-3 text-sm text-green-800">{message}</p>}
    {!loading&&<div className="mt-7 grid gap-5"><fieldset className="grid gap-4 rounded-xl border border-stone-200 bg-white p-5"><legend className="px-2 font-serif text-2xl text-[#173b2c]">Main Services page</legend>{input("main","eyebrow","Eyebrow")}{input("main","title","Hero title",true)}{input("main","description","Hero description",true)}</fieldset><fieldset className="grid gap-4 rounded-xl border border-stone-200 bg-white p-5"><legend className="px-2 font-serif text-2xl text-[#173b2c]">Companionship page</legend>{input("companionship","eyebrow","Eyebrow")}{input("companionship","title","Hero title",true)}{input("companionship","description","Hero description",true)}<div className="grid gap-4 md:grid-cols-2">{input("companionship","primaryCta","Primary button")}{input("companionship","secondaryCta","Secondary link")}{input("companionship","hourlyRate","Hourly rate")}{input("companionship","minimum","Minimum booking")}{input("companionship","startingTotal","Starting total")}</div><div className="grid gap-3"><p className="text-sm font-semibold text-stone-700">Who companionship is for</p>{content.companionship.audience.map((item,index)=><input key={index} aria-label={`Audience item ${index+1}`} className={fieldClass} value={item} onChange={event=>setAudience(index,event.target.value)}/>)}</div></fieldset><fieldset className="grid gap-4 rounded-xl border border-stone-200 bg-white p-5"><legend className="px-2 font-serif text-2xl text-[#173b2c]">Event-planning page</legend>{input("eventPlanning","eyebrow","Eyebrow")}{input("eventPlanning","title","Hero title",true)}{input("eventPlanning","description","Hero description",true)}<div className="grid gap-4 md:grid-cols-2">{input("eventPlanning","primaryCta","Primary button")}{input("eventPlanning","secondaryCta","Secondary link")}</div></fieldset></div>}
  </div></section>;
}
